Repository ManageIQ/dbus_api_service, pull requests merged in 2018-12, with the labels that each got.

#10 Fix travis badge to use the master branch.
  README.md
Labels: documentation

#11 Updated spec tests on failure to not be dependent on lower level dbus library.
  spec/dbus_api_service_spec.rb
Labels: test

#12 Update sinatra minimum to 2.0.2 for Hakiri CVEs
  Gemfile
Labels: dependencies
