Repository ManageIQ/dbus_api_service, pull requests merged in 2020-10, with the labels that each got.

#20 Update stale readme links
  README.md
Labels: developer, documentation

#21 As of Sinatra 2.0.8+: response.body now contains the request
  spec/dbus_api_service_spec.rb
Labels: test

#19 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  .rubocop_local.yml
  Gemfile
Labels: developer, enhancement
